@startuml
skinparam packageStyle rectangle
skinparam backgroundColor #FFFFFF
skinparam usecase {
    BackgroundColor #E2EAF4
    BorderColor #2C3E50
    ArrowColor #2C3E50
    FontName Arial
}

left to right direction

actor "Hệ thống thanh lý tự động\n(Liquidator Bot)" as Bot

rectangle "UC: Tính toán hệ số sức khỏe" {
    
    usecase "Tính toán chỉ số\nHealth Factor (HF)" as UC01
    
    usecase "Lấy thông tin số dư\n(Nợ & Thế chấp)" as Sub1
    usecase "Lấy thông tin giá\ntài sản hiện tại" as Sub2
    
}

Bot --> UC01

' Các nghiệp vụ bắt buộc phải có để tính được HF
UC01 ..> Sub1 : <<include>>
UC01 ..> Sub2 : <<include>>

@enduml
