@startuml
skinparam packageStyle rectangle
skinparam backgroundColor #FFFFFF
skinparam usecase {
    BackgroundColor #E2EAF4
    BorderColor #2C3E50
    ArrowColor #2C3E50
    FontName Arial
}

left to right direction

actor "Liquidator Bot" as Bot

rectangle "UC: Phân tích hiệu quả kinh tế" {
    
    usecase "Phân tích hiệu\nquả kinh tế dự kiến" as UC06
    
    usecase "Truy xuất tài sản và\nquy đổi chi phí mạng (USD)" as Sub1
    usecase "Tính toán lợi nhuận \nthô (Liquidation Bonus)" as Sub2
    usecase "Ước tính chi phí trượt\ngiá và Gas" as Sub3
    usecase "Tính toán lợi\nnhuận ròng (Net Profit)" as Sub4

    usecase "Phân loại giao dịch\nkhông đạt hiệu quả kinh tế" as Ext1
}

Bot --> UC06

' Các luồng sự kiện chính
UC06 ..> Sub1 : <<include>>
UC06 ..> Sub2 : <<include>>
UC06 ..> Sub3 : <<include>>
UC06 ..> Sub4 : <<include>>

' Các luồng ngoại lệ / thay thế
Ext1 .down.> UC06 : <<extend>>\n(Lợi nhuận ròng <= 0 hoặc thấp hơn ngưỡng tối thiểu)

@enduml